version: '3.8'

services:
  cldrive:
    image: cldrive:latest # (prebuilt: ghcr.io/minhkhoi1026/cldrive/cldrive:latest)
    tty: true
    volumes:
      - type: bind
        source: ./docker_data
        target: /home/persistent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # that's the closest analogue to --gpus; provide
              # an integer amount of devices or 'all'
              count: all
              # Devices are reserved using a list of capabilities, making
              # capabilities the only required field. A device MUST 
              # satisfy all the requested capabilities for a successful 
              # reservation.
              capabilities: [ gpu ]
